#preload=$HOME/.config/wallpapers/grove.png
#wallpaper= , $HOME/.config/wallpapers/grove.png

wallpaper {
    monitor = 
    path = $HOME/.config/wallpapers/grove.png
    fit_mode = cover
}

# Remove the cringe splash screen
splash = false